# Generated by Django 6.0.7 on 2026-08-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('instituicao', models.CharField(max_length=100)),
                ('carga_horaria', models.CharField(max_length=30)),
                ('categoria', models.CharField(choices=[('CLOUD', 'Cloud & DevOps'), ('PYTHON', 'Python & Programação'), ('WEB', 'Desenvolvimento Web'), ('FERRAMENTAS', 'Ferramentas & SO')], default='PYTHON', max_length=20)),
                ('codigo_verificacao', models.CharField(blank=True, max_length=150, null=True)),
                ('link_credencial', models.URLField(blank=True, null=True)),
                ('ano', models.CharField(default='2026', max_length=20)),
                ('destaque', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tecnologias', models.CharField(help_text='Separe as tecnologias por vírgula (ex: Python, Django, SQLite)', max_length=200)),
                ('categoria', models.CharField(choices=[('WEB', 'Web / Django'), ('DESKTOP', 'Desktop / GUI'), ('OUTRO', 'Lógica & Outros')], default='WEB', max_length=20)),
                ('link_github', models.URLField(blank=True, null=True)),
                ('link_demo', models.URLField(blank=True, null=True)),
                ('destaque', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
